### ISSUE TITLE
write-good?

### ISSUE THREAD

**Issue by jokeyrhyme** [zeke/npm-collection-language-tools#2]
This might be worth listing here: https://github.com/btford/write-good

**Comment by jokeyrhyme** [comment]
Also, check out its dependencies: https://github.com/btford/write-good/blob/master/package.json

**Comment by zeke** [comment]
Good idea! I added them all: https://github.com/zeke/npm-collection-language-tools#readme

// @btford @RichardLitt

**Comment by RichardLitt** [comment]
:+1:
