### ISSUE TITLE
Several of my natural-language npm modules

### ISSUE THREAD

**Issue by wooorm** [zeke/npm-collection-language-tools#7]
First, thanks for including retext, alex, and franc :+1:

I just checked through my repo’s for some more which might be interesting, and came up with the following:

Word lists:
https://github.com/wooorm/hedges
https://github.com/wooorm/buzzwords
https://github.com/wooorm/profanities
https://github.com/wooorm/fillers
https://github.com/wooorm/weasels
https://github.com/wooorm/afinn-96
https://github.com/wooorm/afinn-111
(maybe also https://github.com/wooorm/gemoji, https://github.com/wooorm/emoticon, and https://github.com/wooorm/emoji-emotion)

Edit distance:
https://github.com/wooorm/dice-coefficient
https://github.com/wooorm/levenshtein-edit-distance (although leven is atm faster 😦 https://github.com/sindresorhus/leven#benchmark)

Phonetics:
https://github.com/wooorm/metaphone
https://github.com/wooorm/double-metaphone
https://github.com/wooorm/stemmer
https://github.com/wooorm/soundex-code

Syllable count:
https://github.com/wooorm/syllable

I can do a PR, but first wanted to know which ones you’d like to add, if at all! 😄

**Comment by zeke** [comment]
Nice. Happy to drop them all in.

I haven't codified the process of submitting a PR to this repo, so I'll do it myself. Stay tuned. :)

**Comment by wooorm** [comment]
Okay that’s also fine, thanks! :+1:

**Comment by wooorm** [comment]
@zeke Ping (:

**Comment by zeke** [comment]
Thanks for the nudge, @wooorm. I just published 1.9.0 to npm

https://github.com/zeke/npm-collection-language-tools#readme

**Comment by wooorm** [comment]
:+1: Cool!
